site_name: App Fepi
site_url: https://example.com/
nav:
  - Inicio: index.md
  - Sobre: about.md
  - Proposta: propostaApp.md
  - Diagramas: diagramas.md
  - Prototipos: prototipos.md
  - Requisitos: requisitos.md

theme:
  name: null
  custom_dir: './material/mkdocs_simple_blog'
  include_search_page: true

  language: pt_br


