site_name: App Fepi
site_url: https://example.com/
nav:
  - Inicio: index.md
  - Sobre: about.md
  - Proposta: propostaApp.md
  - Requisitos: requisitos.md
  - Diagramas: diagramas.md
  - Modelagem: prototipos.md

theme:
  name: null
  custom_dir: './material/mkdocs_dracula_theme'
  include_search_page: true

  language: pt-br


